### ISSUE TITLE
Tracking what's left for the migration to Qt

### ISSUE THREAD

**Issue by ErwanDL** [deepskystacker/DSS#142]
This is a tracking issue to try and list what components are yet to be migrated to Qt 5, and tick what has been done as progress is made. @perdrix52 don't hesitate to edit this or correct me if I'm wrong on this inventory.

## Main components to be migrated to Qt

- [ ] AskRegistering
- [ ] BatchStacking
- [x] CheckAbove (in progress Iustin Amihaesei)
- [x] CometStacking
- [x] ControlPos (updated to support use of HWNDs and well as CWnd*)
- [x] DropFilesDlg
- [x] ExplorerBar
- [x] ImageSinks (obsolescent - replaced by DSS:EditStars and DSS::SelectRect) **still used by ProcessingDlg**
- [x] IntermediateFiles
- [ ] LuminanceTab
- [x] OutputTab
- [x] PostCalibration
- [x] RawDDPSettings
- [x] RecommendedSettings
- [x] RegisterSettings
- [x] ResultParameters
- [x] SaveEditChanges
- [x] SettingsDlg
- [x] StackingDlg  (Believed now completed)
- [x] StackingParameters
- [x] StackRecap
- [x] StackSettings
- [ ] RGBTab
- [ ] SaturationTab
- [x] PictureListCtrl (marked complete but obsolete - replaced by DSS:FrameList and QTableView in StackingDlg
- [ ] ProcessingDlg
- [ ] ProcessSettingsSheet (used by ProcessingDlg)
- [x] ProgressDlg (in progress - Simon Smith)
- [ ] StarMaskDlg
- [ ] SaveEditChanges
- [ ] SavePicture
- [ ] DSSLive/ImageView
- [ ] DSSLive/GraphView
- [ ] DSSLive/ImageList
- [ ] DSSLive/StackedSink
- [ ] DSSLive/LogTab
- [ ] DSSLive/MainBoard
- [ ] DSSLive/Settings
- [ ] DSSLive/RestartMonitoring
- [ ] DSSLive/EmailSettings
- [ ] DSSLive/DeepSkyStackerLiveDlg

## Inventory of Tools/ directory
The legacy GUI widgets live in the `Tools/` directory. Some windows/dialogs listed above depend on these widgets, so we won't be able to migrate them without migrating the underlying widgets to Qt first (or replacing them by their direct Qt equivalent if any). The widgets/files in bold are the ones that seem to be unused. @perdrix52 can we safely delete those to clear up a bit this folder?

- CButtonST: still used in several components: LuminanceTab, RGBTab, SaturationTab, StackingDlg, DSSLive/ImageView
- CButtonToolbar/CButtonToolbarSink: still used by WndImage
- CChildPropertyPage: still used in LuminanceTab, RGBTab, SaturationTab
- CControlPos: still used in ProcessingDlg, DSSLive/GraphView, DSSLive/ImageList, DSSLive/ImageView, DSSLive/LogTab, DSSLive/MainBoard, DSSLive/Settings
- EASYSIZE and related macros: still used in BatchStacking
- CFolderDlg: still used in DSSLive/MainBoard and DSSLive/Settings
- CGradient/CGradientCtrl/CGradientCtrlImpl: still used in ProcessingDlg, RGBTab, DSSLive/ImageView
- CLabel: still used in LuminanceTab, ProcessingDlg, SaturationTab, DSSLive/ImageView, DSSLive/MainBoard, DSSLive/Settings
- CListCtrlEx: still used in PictureListCtrl, DSSLive/ImageList
- CSplitterControl: still used in StackingDlg **Now Removed**
- CToolTipButton: still used in SavePicture
- CWndImage/CWndImageSink: still used in ImageSinks, ProcessingDlg, StackingDlg, DSSLive/ImageView, DSSLive/StackedSink

**Comment by mtoeltsch** [comment]
CSmartPtr/CRefCount: I already replaced them by shared_ptr and/or unique_ptr on a branch locally on my computer. If I find time I could open a new branch and cherry-pick the changes.

**Comment by perdrix52** [comment]
Made updates

**Comment by SimonCSmith** [comment]
New Qt based Progress Dialog completed for main DSS application and DSS CL. DSS Live version pending DSSL updated for Qt.
